import type { BossDef } from './types';

export const BUILT_IN_BOSSES: BossDef[] = [
  {
    id: 'laundry',
    kind: 'laundry',
    name: 'The Laundry Lich',
    chore: 'Fold the laundry',
    unit: 'item',
    unitPlural: 'items',
    countPrompt: 'Count the pile. Every sock counts.',
    hue: 265,
    createdAt: 0,
    builtIn: true,
  },
  {
    id: 'dishes',
    kind: 'dishes',
    name: 'The Sink Warlord',
    chore: 'Wash the dishes',
    unit: 'dish',
    unitPlural: 'dishes',
    countPrompt: 'Count the dishes. Forks count. Lids count.',
    hue: 190,
    createdAt: 0,
    builtIn: true,
  },
  {
    id: 'clutter',
    kind: 'clutter',
    name: 'The Clutter Colossus',
    chore: 'Put the clutter away',
    unit: 'thing',
    unitPlural: 'things',
    countPrompt: 'Count everything that is not where it lives.',
    hue: 25,
    createdAt: 0,
    builtIn: true,
  },
  {
    id: 'bathroom',
    kind: 'bathroom',
    name: 'The Grime Kraken',
    chore: 'Clean the bathroom',
    unit: 'thing',
    unitPlural: 'things',
    countPrompt: 'Count everything that needs a scrub. Taps count. The mirror counts.',
    hue: 150,
    createdAt: 0,
    builtIn: true,
  },
  {
    id: 'bedroom',
    kind: 'bedroom',
    name: 'The Duvet Dragon',
    chore: 'Reset the bedroom',
    unit: 'item',
    unitPlural: 'items',
    countPrompt: 'Count everything that is not where it lives. The chair counts.',
    hue: 330,
    createdAt: 0,
    builtIn: true,
  },
  {
    id: 'floors',
    kind: 'floors',
    name: 'The Dust Devil',
    chore: 'Vacuum and sweep',
    unit: 'thing',
    unitPlural: 'things',
    countPrompt: 'Split the floor into patches and count them. Under the sofa counts.',
    hue: 50,
    createdAt: 0,
    builtIn: true,
  },
  {
    id: 'trash',
    kind: 'trash',
    name: 'The Bin Troll',
    chore: 'Trash and recycling',
    unit: 'item',
    unitPlural: 'items',
    countPrompt: 'Count everything to bin or recycle. Every lid counts.',
    hue: 95,
    createdAt: 0,
    builtIn: true,
  },
];

export function unitWord(boss: BossDef, n: number): string {
  return n === 1 ? boss.unit : boss.unitPlural;
}
